CREATE TABLE EMPLOYEE
(
    ID          NUMBER(10)    NOT NULL,
    FIRSTNAME   VARCHAR2(30),
    LASTNAME    VARCHAR2(30),
    TELEPHONE   VARCHAR2(15),
    EMAIL       VARCHAR2(30),
    CREATED     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT emp_pk PRIMARY KEY (ID)
);

ALTER TABLE EMPLOYEE ADD (CONSTRAINT emp_pk PRIMARY KEY (ID));
ALTER TABLE EMPLOYEE MODIFY CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

CREATE SEQUENCE EMP_SEQ;

--CREATE OR REPLACE TRIGGER EMP_TRG 
--BEFORE INSERT ON EMPLOYEE 
--FOR EACH ROW
--
--BEGIN
--  SELECT EMP_SEQ.NEXTVAL INTO :NEW.id FROM DUAL
--END

SELECT * FROM EMPLOYEE;

CREATE TABLE USERS
(
    USERID     		NUMBER(10)    NOT NULL,
    USERNAME    	VARCHAR2(20),
    PASSWORD   		VARCHAR2(50),
    ISACTIVE   		NUMBER(1),
    USER_ROLE_ID    NUMBER(10),
    CREATED_DATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,     
    CONSTRAINT USERS_PK PRIMARY KEY(USERID)
);

CREATE TABLE USERS_ROLES
(
    USER_ROLE_ID    NUMBER(10)    NOT NULL,
    AUTHORITY    	VARCHAR2(20),
    CREATED_DATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,    
    CONSTRAINT USERS_ROLES_PK PRIMARY KEY(USER_ROLE_ID)
);

INSERT INTO USERS (USERID, USERNAME, PASSWORD, ISACTIVE, USER_ROLE_ID) VALUES
(1, 'karthick', 'admin@123', 1, 1);

INSERT INTO USERS (USERID, USERNAME, PASSWORD, ISACTIVE, USER_ROLE_ID) VALUES
(2, 'kaviya', 'user@123', 1, 2);

INSERT INTO USERS_ROLES (USER_ROLE_ID, AUTHORITY) VALUES (1, 'ROLE_ADMIN');
INSERT INTO USERS_ROLES (USER_ROLE_ID, AUTHORITY) VALUES (2, 'ROLE_USER');

COMMIT

SELECT * FROM USERS;
SELECT * FROM USERS_ROLES;


