-- DROP TRIGGER EMP_TRG
-- DROP SEQUENCE EMP_SEQ
-- DROP TABLE EMPLOYEE

CREATE TABLE EMPLOYEE
(
    ID                NUMBER(10)    NOT NULL,
    FIRSTNAME         VARCHAR2(30),
    LASTNAME          VARCHAR2(30),
    TELEPHONE         VARCHAR2(15),
    EMAIL             VARCHAR2(30)  NOT NULL,
    CREATED_DATE      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT EMP_PK PRIMARY KEY (ID),
    CONSTRAINT EMAIL_UQ UNIQUE (EMAIL)
);

--ALTER TABLE EMPLOYEE ADD CONSTRAINT EMAIL_UQ UNIQUE (EMAIL);
--ALTER TABLE EMPLOYEE ADD (CONSTRAINT emp_pk PRIMARY KEY (ID));
--ALTER TABLE EMPLOYEE MODIFY CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

CREATE SEQUENCE EMP_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE;

CREATE OR REPLACE TRIGGER EMP_TRG 
BEFORE INSERT ON EMPLOYEE 
FOR EACH ROW

BEGIN
  SELECT EMP_SEQ.NEXTVAL INTO :NEW.id FROM DUAL;
END;

-- DROP TRIGGER ROLES_TRG
-- DROP SEQUENCE ROLES_SEQ
-- DROP TABLE ROLES

CREATE TABLE ROLES
(
    ID     		    NUMBER(10)   NOT NULL,
    ROLE    	    VARCHAR2(20) NOT NULL,   
    CREATED_DATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT ROLES_PK PRIMARY KEY(ID)
);

CREATE SEQUENCE ROLES_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE;

CREATE OR REPLACE TRIGGER ROLES_TRG 
BEFORE INSERT ON ROLES 
FOR EACH ROW

BEGIN
  SELECT ROLES_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

-- DROP TRIGGER USERS_TRG
-- DROP SEQUENCE USERS_SEQ
-- DROP TABLE USERS

CREATE TABLE USERS
(
    USERID     		NUMBER(10) NOT NULL,
    USERNAME    	VARCHAR2(20) NOT NULL,
    PASSWORD   		VARCHAR2(50) NOT NULL,
    ISACTIVE   		NUMBER(1),    
    CREATED_DATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT USERS_PK PRIMARY KEY(USERID)
);

CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1 NOMAXVALUE;

CREATE OR REPLACE TRIGGER USERS_TRG 
BEFORE INSERT ON USERS 
FOR EACH ROW

BEGIN
  SELECT USERS_SEQ.NEXTVAL INTO :new.USERID from DUAL;
END;

-- DROP TABLE USERS_ROLES

CREATE TABLE USERS_ROLES
(
    USER_ID       NUMBER(10)  NOT NULL,
    ROLE_ID    	  VARCHAR2(20) NOT NULL,
    CREATED_DATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,    

    CONSTRAINT USER_ID_UQ UNIQUE (USER_ID),
    CONSTRAINT ROLE_ID_UQ UNIQUE (ROLE_ID)
);

INSERT INTO ROLES (ROLE) VALUES('admin'); 
INSERT INTO ROLES (ROLE) VALUES('moderator'); 
INSERT INTO ROLES (ROLE) VALUES('user'); 

INSERT INTO USERS (USERNAME, PASSWORD, ISACTIVE) VALUES ('karthick', 'admin@123', 1);
INSERT INTO USERS (USERNAME, PASSWORD, ISACTIVE) VALUES ('kaviya', 'user@123', 1);

INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (2, 2);

COMMIT;

SELECT * FROM ROLES;
SELECT * FROM USERS;
SELECT * FROM USERS_ROLES;
SELECT * FROM EMPLOYEE;
SELECT * FROM CUSTOMER;
SELECT * FROM CUSTOMER_DETAIL;
SELECT * FROM SCHOOL;
SELECT * FROM ACCOUNTS;
SELECT * FROM PROJECT;
SELECT * FROM MODULE;
SELECT * FROM TASK;
SELECT * FROM PERSON;
SELECT * FROM PERSONDETAIL;
SELECT * FROM COLLEGE;
SELECT * FROM STUDENT;
SELECT * FROM Delegate;
SELECT * FROM Event;
SELECT * FROM JOIN_DELEGATE_EVENT;

