CREATE TABLE EMPLOYEE
(
    ID                INT(10) NOT NULL AUTO_INCREMENT,
    FIRSTNAME         VARCHAR(30),
    LASTNAME          VARCHAR(30),
    TELEPHONE         VARCHAR(15),
    EMAIL             VARCHAR(30)  NOT NULL,
    CREATED_DATE      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (ID),
    UNIQUE KEY (EMAIL)
);

CREATE TABLE ROLES
(
    ID     		    INT(10)   	NOT NULL AUTO_INCREMENT,
    ROLE    	    VARCHAR(20) NOT NULL,   
    CREATED_DATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY(ID)
);

CREATE TABLE USERS
(
    USERID     		INT(10)		NOT NULL AUTO_INCREMENT,
    USERNAME    	VARCHAR(20) NOT NULL,
    PASSWORD   		VARCHAR(50) NOT NULL,
    ISACTIVE   		INT(1),    
    CREATED_DATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY(USERID)
);

CREATE TABLE USERS_ROLES
(
    USER_ID       INT(10)  NOT NULL,
    ROLE_ID    	  VARCHAR(20) NOT NULL,
    CREATED_DATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,    

    UNIQUE KEY (USER_ID, ROLE_ID)
);

INSERT INTO ROLES (ROLE) VALUES('admin'); 
INSERT INTO ROLES (ROLE) VALUES('moderator'); 
INSERT INTO ROLES (ROLE) VALUES('user'); 

INSERT INTO USERS (USERNAME, PASSWORD, ISACTIVE) VALUES ('karthick', 'admin@123', 1);
INSERT INTO USERS (USERNAME, PASSWORD, ISACTIVE) VALUES ('kaviya', 'user@123', 1);

INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USERS_ROLES (USER_ID, ROLE_ID) VALUES (2, 2);

SELECT * FROM ROLES;
SELECT * FROM USERS;
SELECT * FROM USERS_ROLES;
SELECT * FROM EMPLOYEE;
